/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type NFInstancesStoreAPI struct {
}

// Get /nnrf-nfm/v1/nf-instances
// Retrieves a collection of NF Instances 
func (api *NFInstancesStoreAPI) GetNFInstances(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Options /nnrf-nfm/v1/nf-instances
// Discover communication options supported by NRF for NF Instances 
func (api *NFInstancesStoreAPI) OptionsNFInstances(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

