/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type SubscriptionIDDocumentAPI struct {
}

// Delete /nnrf-nfm/v1/subscriptions/:subscriptionID
// Deletes a subscription 
func (api *SubscriptionIDDocumentAPI) RemoveSubscription(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Patch /nnrf-nfm/v1/subscriptions/:subscriptionID
// Updates a subscription 
func (api *SubscriptionIDDocumentAPI) UpdateSubscription(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

