/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type NFInstanceIDDocumentAPI struct {
}

// Delete /nnrf-nfm/v1/nf-instances/:nfInstanceID
// Deregisters a given NF Instance 
func (api *NFInstanceIDDocumentAPI) DeregisterNFInstance(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /nnrf-nfm/v1/nf-instances/:nfInstanceID
// Read the profile of a given NF Instance 
func (api *NFInstanceIDDocumentAPI) GetNFInstance(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Put /nnrf-nfm/v1/nf-instances/:nfInstanceID
// Register a new NF Instance 
func (api *NFInstanceIDDocumentAPI) RegisterNFInstance(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Patch /nnrf-nfm/v1/nf-instances/:nfInstanceID
// Update NF Instance profile 
func (api *NFInstanceIDDocumentAPI) UpdateNFInstance(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

