/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type SharedDataDocumentAPI struct {
}

// Delete /nnrf-nfm/v1/shared-data/:sharedDataId
// Delete Shared Data identified by a given sharedDataId 
func (api *SharedDataDocumentAPI) DeleteSharedData(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /nnrf-nfm/v1/shared-data/:sharedDataId
// Read the shared data identified by a given NF sharedDataId 
func (api *SharedDataDocumentAPI) GetSharedData(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Put /nnrf-nfm/v1/shared-data/:sharedDataId
// Register new Shared Data 
func (api *SharedDataDocumentAPI) RegisterSharedData(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Patch /nnrf-nfm/v1/shared-data/:sharedDataId
// Update Shared Data 
func (api *SharedDataDocumentAPI) UpdateSharedData(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

