/*
 * NRF Bootstrapping
 *
 * NRF Bootstrapping.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type BootstrappingRequestAPI struct {
}

// Get /bootstrapping
// Bootstrapping Info Request 
func (api *BootstrappingRequestAPI) BootstrappingInfoRequest(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

