/*
 * NSSF NSSAI Availability
 *
 * NSSF NSSAI Availability Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type NSSAIAvailabilityStoreAPI struct {
}

// Options /nnssf-nssaiavailability/v1/nssai-availability
// Discover communication options supported by NSSF for NSSAI Availability 
func (api *NSSAIAvailabilityStoreAPI) NSSAIAvailabilityOptions(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

