/*
 * NSSF NSSAI Availability
 *
 * NSSF NSSAI Availability Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type NFInstanceIDDocumentAPI struct {
}

// Delete /nnssf-nssaiavailability/v1/nssai-availability/:nfId
// Deletes an already existing S-NSSAIs per TA provided by the NF service consumer (e.g AMF) 
func (api *NFInstanceIDDocumentAPI) NSSAIAvailabilityDelete(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Patch /nnssf-nssaiavailability/v1/nssai-availability/:nfId
// Updates an already existing S-NSSAIs per TA provided by the NF service consumer (e.g AMF) 
func (api *NFInstanceIDDocumentAPI) NSSAIAvailabilityPatch(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Put /nnssf-nssaiavailability/v1/nssai-availability/:nfId
// Updates/replaces the NSSF with the S-NSSAIs the NF service consumer (e.g AMF)supports per TA 
func (api *NFInstanceIDDocumentAPI) NSSAIAvailabilityPut(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

