/*
 * NSSF NSSAI Availability
 *
 * NSSF NSSAI Availability Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type MitigationInfo struct {

	PercValueNumUes int32 `json:"percValueNumUes,omitempty"`

	NewUesInd bool `json:"newUesInd,omitempty"`
}
