/*
 * NSSF NSSAI Availability
 *
 * NSSF NSSAI Availability Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// SnssaiReplaceInfo - Indicates the status of an S-NSSAI and optionally an alternative S-NSSAI.
type SnssaiReplaceInfo struct {

	Snssai Snssai `json:"snssai"`

	Status SnssaiStatus `json:"status"`

	AltSnssai Snssai `json:"altSnssai,omitempty"`
}
