/*
 * NRF Bootstrapping
 *
 * NRF Bootstrapping.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Status - Overal status of the NRF
type Status struct {
}
