/*
 * NSSF NS Selection
 *
 * NSSF Network Slice Selection Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// QueryParameter - Contains the name and value of a query parameter
type QueryParameter struct {

	Name string `json:"name"`

	Value string `json:"value"`
}
