/*
 * NRF NFDiscovery Service
 *
 * NRF NFDiscovery Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// CnfUnit - During the processing of cnfUnits attribute, all the members in the array shall be  interpreted as logically concatenated with logical \"AND\". 
type CnfUnit struct {

	CnfUnit []Atom `json:"cnfUnit"`
}
