/*
 * NSSF NS Selection
 *
 * NSSF Network Slice Selection Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// AllowedSnssai - Contains the authorized S-NSSAI and optional mapped home S-NSSAI and network slice instance information 
type AllowedSnssai struct {

	AllowedSnssai Snssai `json:"allowedSnssai"`

	NsiInformationList []NsiInformation `json:"nsiInformationList,omitempty"`

	MappedHomeSnssai Snssai `json:"mappedHomeSnssai,omitempty"`
}
