/*
 * NSSF NS Selection
 *
 * NSSF Network Slice Selection Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// SliceInfoForRegistration - Contains the slice information requested during a Registration procedure
type SliceInfoForRegistration struct {

	SubscribedNssai []SubscribedSnssai `json:"subscribedNssai,omitempty"`

	AllowedNssaiCurrentAccess AllowedNssai `json:"allowedNssaiCurrentAccess,omitempty"`

	AllowedNssaiOtherAccess AllowedNssai `json:"allowedNssaiOtherAccess,omitempty"`

	SNssaiForMapping []Snssai `json:"sNssaiForMapping,omitempty"`

	RequestedNssai []Snssai `json:"requestedNssai,omitempty"`

	DefaultConfiguredSnssaiInd bool `json:"defaultConfiguredSnssaiInd,omitempty"`

	MappingOfNssai []MappingOfSnssai `json:"mappingOfNssai,omitempty"`

	RequestMapping bool `json:"requestMapping,omitempty"`

	UeSupNssrgInd bool `json:"ueSupNssrgInd,omitempty"`

	SuppressNssrgInd bool `json:"suppressNssrgInd,omitempty"`

	NsagSupported bool `json:"nsagSupported,omitempty"`
}
