/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// NwdafCapability - Indicates the capability supported by the NWDAF
type NwdafCapability struct {

	AnalyticsAggregation bool `json:"analyticsAggregation,omitempty"`

	AnalyticsMetadataProvisioning bool `json:"analyticsMetadataProvisioning,omitempty"`

	MlModelAccuracyChecking bool `json:"mlModelAccuracyChecking,omitempty"`

	AnalyticsAccuracyChecking bool `json:"analyticsAccuracyChecking,omitempty"`
}
