/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Tmgi - Temporary Mobile Group Identity
type Tmgi struct {

	// MBS Service ID
	MbsServiceId string `json:"mbsServiceId" validate:"regexp=^[A-Fa-f0-9]{6}$"`

	PlmnId PlmnId `json:"plmnId"`
}
