/*
 * NSSF NSSAI Availability
 *
 * NSSF NSSAI Availability Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// SupportedNssaiAvailabilityData - This contains the Nssai availability data information per TA supported by the AMF
type SupportedNssaiAvailabilityData struct {

	Tai Tai `json:"tai"`

	SupportedSnssaiList []ExtSnssai `json:"supportedSnssaiList"`

	TaiList []Tai `json:"taiList,omitempty"`

	TaiRangeList []TaiRange `json:"taiRangeList,omitempty"`

	NsagInfos []NsagInfo `json:"nsagInfos,omitempty"`
}
