/*
 * NSSF NSSAI Availability
 *
 * NSSF NSSAI Availability Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// SnssaiReplaceInfo - Indicates the status of an S-NSSAI and an alternative S-NSSAI optionally.
type SnssaiReplaceInfo struct {

	Snssai Snssai `json:"snssai"`

	Status SnssaiStatus `json:"status,omitempty"`

	AltSnssai Snssai `json:"altSnssai,omitempty"`

	NsReplTerminInd TerminationIndication `json:"nsReplTerminInd,omitempty"`

	PlmnId PlmnId `json:"plmnId,omitempty"`

	MitigationInfo MitigationInfo `json:"mitigationInfo,omitempty"`
}
