/*
 * NSSF NS Selection
 *
 * NSSF Network Slice Selection Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// NoProfileMatchInfo - Provides the reason for not finding NF matching the search criteria
type NoProfileMatchInfo struct {

	Reason NoProfileMatchReason `json:"reason"`

	QueryParamCombinationList []QueryParamCombination `json:"queryParamCombinationList,omitempty"`
}
