/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type RuleSet struct {

	Priority int32 `json:"priority"`

	Plmns []PlmnId `json:"plmns,omitempty"`

	Snpns []PlmnIdNid `json:"snpns,omitempty"`

	NfTypes []NfType `json:"nfTypes,omitempty"`

	NfDomains []string `json:"nfDomains,omitempty"`

	Nssais []ExtSnssai `json:"nssais,omitempty"`

	NfInstances []string `json:"nfInstances,omitempty"`

	Scopes []string `json:"scopes,omitempty"`

	// Specifies whether access/scope is allowed or denied for a specific NF-Consumer.      anyOf: - type: string   enum:     - ALLOW     - DENY - type: string 
	Action *interface{} `json:"action"`
}
