/*
 * NRF OAuth2
 *
 * NRF OAuth2 Authorization.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// MlModelInterInd1 - ML Model Interoperability Indicator per Analytics Id
type MlModelInterInd1 struct {

	AnalyticsId NwdafEvent `json:"analyticsId"`

	VendorList []string `json:"vendorList"`
}
