/*
 * NSSF NS Selection
 *
 * NSSF Network Slice Selection Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// MappingOfSnssai - Contains the mapping of S-NSSAI in the serving network and the value of the home network 
type MappingOfSnssai struct {

	ServingSnssai Snssai `json:"servingSnssai"`

	HomeSnssai Snssai `json:"homeSnssai"`
}
