/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// AfEventExposureData - AF Event Exposure data managed by a given NEF Instance
type AfEventExposureData struct {

	AfEvents []AfEvent `json:"afEvents"`

	AfIds []string `json:"afIds,omitempty"`

	AppIds []string `json:"appIds,omitempty"`

	TaiList []Tai `json:"taiList,omitempty"`

	TaiRangeList []TaiRange `json:"taiRangeList,omitempty"`
}
