/*
 * NSSF NSSAI Availability
 *
 * NSSF NSSAI Availability Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// SnssaiReplacementSubscribeInfo - Present if the NF service consumer subscribes to events related to Network Slice Replacement. 
type SnssaiReplacementSubscribeInfo struct {

	SnssaiToSubscribe []Snssai `json:"snssaiToSubscribe"`

	NfType NfType `json:"nfType"`

	// String uniquely identifying a NF instance. The format of the NF Instance ID shall be a  Universally Unique Identifier (UUID) version 4, as described in IETF RFC 4122.  
	NfId string `json:"nfId"`

	PlmnId PlmnId `json:"plmnId,omitempty"`
}
