/*
 * NSSF NS Selection
 *
 * NSSF Network Slice Selection Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// SubscribedSnssai - Contains the subscribed S-NSSAI
type SubscribedSnssai struct {

	SubscribedSnssai Snssai `json:"subscribedSnssai"`

	DefaultIndication bool `json:"defaultIndication,omitempty"`

	SubscribedNsSrgList []string `json:"subscribedNsSrgList,omitempty"`
}
