/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// SmsfInfo - Specific Data for SMSF
type SmsfInfo struct {

	RoamingUeInd bool `json:"roamingUeInd,omitempty"`

	RemotePlmnRangeList []PlmnRange `json:"remotePlmnRangeList,omitempty"`
}
