/*
 * NSSF NS Selection
 *
 * NSSF Network Slice Selection Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// TacRange - Range of TACs (Tracking Area Codes)
type TacRange struct {

	Start string `json:"start,omitempty"`

	End string `json:"end,omitempty"`

	Pattern string `json:"pattern,omitempty"`
}
