/*
 * NSSF NS Selection
 *
 * NSSF Network Slice Selection Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// MlModelInterInd - ML Model Interoperability Indicator per Analytics Id
type MlModelInterInd struct {

	AnalyticsId NwdafEvent `json:"analyticsId"`

	VendorList []string `json:"vendorList"`
}
